language: node_js
sudo: false
node_js:
  - 5
install:
  - npm install -g nativefier
script:
  - make all
deploy:
  provider: releases
  api_key: ZZHW49/kJWAUFQ4wSGyBe8HpAx5yiDueDWddRCS+vd9U51fz71LOmgSA4nXtJMa9vsN/sYinQF9p0vJXctJShFgtenA7GemqhYUsylptRK8HyV1Sqmobv8fQcp1vRJWzNHQjdegyNK2w3pYNY88Tz+lmP9pTmiq+Ff5nEzYlnzyGCqwcrb6cmqB/Ple59BWeaxf1iYcA0k/s3rHPmPk1i1zp6PU0X6sRzUpgBxYeg3nVMPYH0yqbMBHLeMAX7f1pd7yTMdhldeRpXv6qJr9cyXqDbYDHHnPKhpTSg6tfgceWo2Ez+HnbDh+cdGcVEeRx+gENBjZWC+RLDnEq9jz5hXY2PnDZGnaV92+zfs1ughm+o/BbjFxWg9u3sfn1RQWjwiWzghCJb6EqkvgmAIF+L/aYG0JE+GFmtx3QRyZ8ecfqnRGph9P9MfHwNnoLisLMvyB+YlwTH1Detg7xXxVU9OGH8JIfztUaFmoN+9jrMOe2gwFHVfR26mTK3V9G8EwcbNDhARVHC+CX7n8mMT5VXuhb/gPJQxuqad795nEYTY1l+R1kfwmxmcJpHWYomEZSUMXMeQurtG4rWj61ITMov+GF+4aoCn1DxuJS71M54Gz26owM7xllI+EAYwY+fw8sBO7jJYVWwvKwbonqtgL76/soG6/MVJmGLpMuzpKVI5g=
  file:
    - DayNhauHoc-darwin-x64.tar.gz
    - DayNhauHoc-linux-x64.tar.gz
    - DayNhauHoc-win32-x64.tar.gz
  skip_cleanup: true
  'on':
    tags: true
env:
  global:
    - secure: ZZHW49/kJWAUFQ4wSGyBe8HpAx5yiDueDWddRCS+vd9U51fz71LOmgSA4nXtJMa9vsN/sYinQF9p0vJXctJShFgtenA7GemqhYUsylptRK8HyV1Sqmobv8fQcp1vRJWzNHQjdegyNK2w3pYNY88Tz+lmP9pTmiq+Ff5nEzYlnzyGCqwcrb6cmqB/Ple59BWeaxf1iYcA0k/s3rHPmPk1i1zp6PU0X6sRzUpgBxYeg3nVMPYH0yqbMBHLeMAX7f1pd7yTMdhldeRpXv6qJr9cyXqDbYDHHnPKhpTSg6tfgceWo2Ez+HnbDh+cdGcVEeRx+gENBjZWC+RLDnEq9jz5hXY2PnDZGnaV92+zfs1ughm+o/BbjFxWg9u3sfn1RQWjwiWzghCJb6EqkvgmAIF+L/aYG0JE+GFmtx3QRyZ8ecfqnRGph9P9MfHwNnoLisLMvyB+YlwTH1Detg7xXxVU9OGH8JIfztUaFmoN+9jrMOe2gwFHVfR26mTK3V9G8EwcbNDhARVHC+CX7n8mMT5VXuhb/gPJQxuqad795nEYTY1l+R1kfwmxmcJpHWYomEZSUMXMeQurtG4rWj61ITMov+GF+4aoCn1DxuJS71M54Gz26owM7xllI+EAYwY+fw8sBO7jJYVWwvKwbonqtgL76/soG6/MVJmGLpMuzpKVI5g=
