language: node_js
sudo: false
node_js:
  - 5
install:
  - npm install -g nativefier
script:
  - make all
deploy:
  provider: releases
  api_key: evdqs3jwIg2BDkrOOCazIoKMYBYzb6yV2GmgeHb4Kw5A/HzGLEelhfEQfMOYQk4M3xJOu5BlbDRqRALqo2YP7DBCSrD/m8M3+KmBriXkK8eTs7sn0aTpXnw2qezbFbrXgKUTQDDtfkXOYBD0sZR7RQKhVNXZZs29mUyBUmP2Dm+M6QVXY/YXJOAAg9F0hwpXrR6QzNuN7KnAgS5plyS7Txo6ARtNr6bnW7MyLqq6WXsVz9r0i2I3xBr+oS/mpU/ieXSmaCZWWQD28KX8Agz1Cof2ZhIGYadiJe2joP1KlCiQ+fQSwN210M5JBryldHEJ54rtcs5qNgFWWPlXufIARwTcjg7AlHQ/3badDjZYrOImJ3BhQeMeARGEai4VZxJj6UXcD1wW5uB/sjdNadzqhiIo/EF/mgyt1IZf+3iUuBzMlv5GbfYW/2c+jwYjlP94zdHuJX0TiF9medx6/EWS8AGl4UM8dXzlAe/JWMpdi/MQsp5r/Dl36FMmofnjbwAL/9tVuz2PElssr2nWKl44h2LXUNnb1vfn6goTc/nBTN6ry8fcArQm9oAoDJlawGRAcYuk9q7AiVz8QR0bfxnSB4DzkO7HdhBZQljVxBmgOm5fl/JfxbIzcGNexp6YUX/iHsYFC5i6LBHu4IK7UrkODQEDwc/y34LhnhGwrNIzEDk=
  file:
    - DayNhauHoc-darwin-x64.tar.gz
    - DayNhauHoc-linux-x64.tar.gz
    - DayNhauHoc-win32-x64.tar.gz
  skip_cleanup: true
  'on':
    tags: true
env:
  global:
    - secure: evdqs3jwIg2BDkrOOCazIoKMYBYzb6yV2GmgeHb4Kw5A/HzGLEelhfEQfMOYQk4M3xJOu5BlbDRqRALqo2YP7DBCSrD/m8M3+KmBriXkK8eTs7sn0aTpXnw2qezbFbrXgKUTQDDtfkXOYBD0sZR7RQKhVNXZZs29mUyBUmP2Dm+M6QVXY/YXJOAAg9F0hwpXrR6QzNuN7KnAgS5plyS7Txo6ARtNr6bnW7MyLqq6WXsVz9r0i2I3xBr+oS/mpU/ieXSmaCZWWQD28KX8Agz1Cof2ZhIGYadiJe2joP1KlCiQ+fQSwN210M5JBryldHEJ54rtcs5qNgFWWPlXufIARwTcjg7AlHQ/3badDjZYrOImJ3BhQeMeARGEai4VZxJj6UXcD1wW5uB/sjdNadzqhiIo/EF/mgyt1IZf+3iUuBzMlv5GbfYW/2c+jwYjlP94zdHuJX0TiF9medx6/EWS8AGl4UM8dXzlAe/JWMpdi/MQsp5r/Dl36FMmofnjbwAL/9tVuz2PElssr2nWKl44h2LXUNnb1vfn6goTc/nBTN6ry8fcArQm9oAoDJlawGRAcYuk9q7AiVz8QR0bfxnSB4DzkO7HdhBZQljVxBmgOm5fl/JfxbIzcGNexp6YUX/iHsYFC5i6LBHu4IK7UrkODQEDwc/y34LhnhGwrNIzEDk=
